petProject/home/urls.py
from django.urls import path
from django.contrib.auth import login
from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("contact-us/", views.contact_us, name="contact"),
]

petProject/petProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("post.urls")),
    path("", include("user.urls")),
    path("", include("django.contrib.auth.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petProject/user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import login
from django.contrib.auth import views as auth_views

app_name = "user"


urlpatterns = [
    path("sign-up/", views.sign_up, name="sign_up"),
    path("<str:username>/profile/", views.profile, name="profile"),
    path("<str:username>/edit-profile/", views.edit_profile, name="edit-profile"),
    path("<str:username>/follow/", views.follow, name="follow"),
    path("profile-photo/", views.profile_photo, name="profile-photo"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path("password_change/", views.change_password, name="change_password"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

petProject/post/models.py
from django.db import models
from user.models import Account


# Create your models here.


class Post(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True, null=False)
    caption = models.CharField(max_length=1000, null=True)
    is_active = models.BooleanField(default=True)
    is_archived = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    likes = models.ManyToManyField(Account, related_name="like_post", blank=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, null=True, on_delete=models.CASCADE)
    comment = models.CharField(max_length=500, null=True)
    reply = models.ForeignKey(
        "self", null=True, related_name="replies", on_delete=models.CASCADE
    )
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    likes = models.ManyToManyField(Account, related_name="like_comment", blank=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)


class Image(models.Model):
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, null=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/", null=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)

petProject/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, User
from datetime import date

# Create your models here.


class AccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Please provide a valid email address")
        if not username:
            raise ValueError("Please provide a valid username")

        user = self.model(email=self.normalize_email(email), username=username,)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email), username=username, password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True

        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=100, unique=True)
    username = models.CharField(verbose_name="username", max_length=50, unique=True)
    name = models.CharField(verbose_name="name", max_length=50, null=True)
    breed = models.CharField(max_length=30, null=True, blank=True)
    animal = models.CharField(max_length=50, null=True, blank=True)
    profile_photo = models.ImageField(upload_to="images/", blank=True)
    bio = models.TextField(null=True, blank=True)
    date_of_birth = models.DateField(
        help_text="Please use the following format: <em>YYYY-MM-DD</em>.",
        null=True,
        blank=True,
    )
    date_joined = models.DateTimeField(
        verbose_name="date joined", auto_now=False, auto_now_add=True
    )
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]
    objects = AccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


class Follow(models.Model):
    account = models.ForeignKey(Account, null=True, on_delete=models.CASCADE)
    followers = models.ManyToManyField(Account, related_name="following")
    following = models.ManyToManyField(Account, related_name="followers")

    def __unicode__(self):
        return u"%s follows %s" % (self.follower, self.following)

petProject/user/forms.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import Account


class SignUpForm(UserCreationForm):
    class Meta:
        model = Account
        fields = [
            "username",
            "email",
            "breed",
            "animal",
            "bio",
            "date_of_birth",
            "password1",
            "password2",
        ]


class SignUpEditForm(ModelForm):
    class Meta:
        model = Account
        fields = [
            "username",
            "email",
            "breed",
            "animal",
            "bio",
            "date_of_birth",
        ]

petProject/user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm, PasswordChangeForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from .models import Account, Follow
from .forms import SignUpForm, SignUpEditForm
from post.forms import ImageForm
from post.models import Post, Comment, Image

# Create your views here.
def password_reset_request(request):
    if request.method == "POST":
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data["email"]
            users = Account.objects.filter(Q(email=data) | Q(username=data))
            if users.exists():
                for user in users:
                    subject = "Password Reset Requested"
                    email_template_name = "password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        "domain": "127.0.0.1:8000",
                        "site_name": "The Pet Gallery",
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        "token": default_token_generator.make_token(user),
                        "protocol": "http",
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(
                            subject,
                            email,
                            "admin@example.com",
                            [user.email],
                            fail_silently=False,
                        )
                    except BadHeaderError:
                        return HttpResponse("Invalid header found.")
                    return redirect("/password_reset/done/")
    form = PasswordResetForm()
    return render(request, "password/password_reset.html", {"form": form},)


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Your password was successfully updated")
            return redirect("home:profile")
        else:
            messages.error(request, "Oops something is not right")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, "password/password_change.html", {"form": form})


def sign_up(request):
    if request.method == "POST":
        form = SignUpForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
        return redirect("/login")
    else:
        form = SignUpForm()
    return render(request, "registration/sign_up.html", {"form": form})


def profile_photo(request):
    account = Account.objects.get(email=request.user)
    if Image.objects.filter(account=account).exists():
        return redirect("home:index")
    else:
        if request.method == "POST":
            form = ImageForm(request.POST or None, request.FILES or None)
            if form.is_valid():
                photo = form.save(commit=False)
                photo.account = request.user
                if photo.image:
                    photo.save()
                else:
                    photo.image = "static/default_img.jpg"
                    photo.save()
                return redirect("home:index")
        else:
            form = ImageForm()
        return render(request, "profile/profile_photo.html", {"form": form})


def profile(request, username):
    account = Account.objects.get(username=username)
    posts = Post.objects.filter(account=account, is_active=True).order_by("-date")
    try:
        image = Image.objects.get(account=account)
        user_follow = Follow.objects.get(account=account)
        account_follow = Follow.objects.get(account=request.user)
        followers = user_follow.followers.all()
        following = user_follow.following.all()
        if request.method == "POST":
            if "follow" in request.POST:
                print(request.POST)
                follow2.followers.add(request.user)
                follow.following.add(account)
                follow2.save()
                follow.save()
                return redirect(request.path_info)
            if "unfollow" in request.POST:
                follow2.followers.remove(request.user)
                follow.following.remove(account)
                follow2.save()
                follow.save()
                return redirect(request.path_info)
    except:
        image = None
        follow2 = None
        follow = None

    return render(
        request,
        "profile/profile.html",
        {"account": account, "posts": posts, "image": image},
    )


def edit_profile(request, username):
    form_class = SignUpEditForm
    account = get_object_or_404(Account, username=username)
    form = form_class(request.POST, request.FILES, instance=account)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, "Profile successfully updated")
            return redirect("profile:profile", username=request.user.username)
    else:
        form = SignUpEditForm(instance=account)
    return render(request, "profile/edit_profile.html", {"form": form})


def follow(request, username):
    try:
        follow = Follow.objects.get(account=request.user)
        followers = follow.followers.all()
        following = follow.following.all()
        if request.method == "POST":
            print(request.POST)
            if "follow" in request.POST:
                account = Account.objects.get(email=request.POST.get("follow"))
                print(request.POST.get("follow"))
                following.add(request.user)
                following.save()
                return redirect(request.path_info)
            if "unfollow" in request.POST:
                print(request.POST.get("unfollow"))
                account = Account.objects.get(email=request.POST.get("unfollow"))
                following.remove()
                following.save()
                return redirect(request.path_info)
    except DoesNotExist:
        follow = None

    return render(
        request,
        "profile/follow.html",
        {"follow": follow, "followers": followers, "following": following},
    )
    pass

petProject/user/templates/profile/edit_profile.html
{% extends 'home/base_layout.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="card">
  <div class="details-header">
    <h2 style="margin-top:30px" >Edit profile</h2>
  </div>
  <div class="details-buttons">
    <hr>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <a href="/{{ request.user.username }}/profile"><button style="color:red; margin-bottom: 30px" id="button-hover" type="button" class="btn">Cancel</button></a>
      <button type="submit" style="color:blue; margin-bottom: 30px;" id="button-hover"  class="btn">Update profile</button>
    </form>
  </div>

</div>
{% endblock %}

petProject/user/templates/profile/follow.html
{% extends 'home/base_layout.html' %}
  {% block content %}
<div class="card">
  <div class="details-header">
    <h2 style="margin-top:30px">Followers and Following</h2>
  </div>
  <div class="details-buttons">
    <hr>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#home">Followers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#profile">Following</a>
      </li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active show" id="home">
        {% if follow == None %}
          <div class="no-follow">
            <h4>No followers yet</h4>
          </div>
        {% else %}
          <ul class="follow">
            {% for follower in followers %}
              <li>
                <a href="#">{{ follower.username }}</a>
              </li>
              <hr>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
      <div class="tab-pane fade" id="profile">
        {% if follow == None %}
          <div class="no-follow">
            <h4>No following anyone yet</h4>
          </div>
        {% else %}
          <ul class="follow">
            {% for follow in following %}
              <li>
                <div class="">
                  <a href="#">{{ follow.username }}</a>
                </div>
                <div class="">
                  <form method="post">
                    {% csrf_token %}
                    <button type="submit" name="unfollow" value="{{ follow }}" class="btn">Unfollow</button>
                  </form>
                </div>
              </li>
              <hr>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

petProject/user/templates/profile/profile.html
{% extends 'home/base_layout.html' %}
{% load static %}
{% if user.is_authenticated %}
  {% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% include 'home/alerts.html' %}
      <div class="background">
        <div class="details-header">
          <div class="profile-picture">
            {% if image == None %}
              <img src="{% static 'default_img.jpg' %}" alt="">
            {% else %}
              <img src="{{ image.image.url }}" alt="Profile Photo">
            {% endif %}
          </div>
          <div class="profile-info">
            <ul>
              {% if account.username %}
                <li>Username: {{ account.username | title  }}</li>
              {% endif %}
              {% if account.animal %}
                <li>Animal: {{ account.animal | title }}</li>
              {% endif %}
              {% if account.breed %}
                <li>Breed: {{ account.breed | title }}</li>
              {% endif %}
              {% if account.bio %}
                <li>Bio: {{ account.bio | title }}</li>
              {% endif %}
            </ul>
          </div>
          <div class="follow">
            <a href="/{{ account.username }}/follow">
              <h6>Follows</h6>
            </a>

            <form  method="post">
              {% csrf_token %}
              <button type="submit" name="follow" class="btn"> Follow</button>
            </form>
            <form method="post">
              {% csrf_token %}
              <button type="submit" name="unfollow" class="btn">Unfollow</button>
            </form>

          </div>
            {% if account == request.user %}
            <div class="btn-group dropright" style="width:70px; height:50px; margin-top:20px">
              <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                </svg>
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="link-hover"  href="/{{ request.user.username }}/edit-profile">
                  <button type="button" name="archive" id="button-hover" style="color:blue" class="dropdown-item">Edit Profile</button>
                </a>
                <a class="link-hover"  href="/profile-photo">
                  <button type="button" name="archive" id="button-hover" style="color:blue" class="dropdown-item">Update profile picture</button>
                </a>
                <a class="link-hover"  href="/{{ account.username }}/archive">
                  <button type="button" name="archive" id="button-hover" style="color:blue" class="dropdown-item">Archive</button>
                </a>
                <a class="link-hover"  href="/password_change">
                  <button style="color:blue" id="button-hover" class="dropdown-item" type="button">Change password</button>
                </a>
                <a class="link-hover" href="/logout">
                  <button style="color:red" class="dropdown-item" type="button">Logout</button>
                </a>

              </div>
            </div>
            {% endif %}
      </div>

    </div>
<div class="details-buttons">
  {% if posts %}
  <ul class="profile-posts">
    {% for post in posts %}
    <li>
      <div class="post-card">
        {% for image in post.image_set.all %}
          {% if forloop.first %}
            <a href="/{{ post.id }}/view"><img class="card-image" src="{{ image.image.url }}" alt="Pet image"></a>
          {% endif %}
        {% endfor %}
      </div>
    </li>
    {% endfor %}
  {% else %}
      <div class="no-post">
        <img src="https://img.icons8.com/clouds/100/000000/dog-paw-print.png"/>
        <div class="">
          <h5>No post yet <a style="color:blue;" href="/create">Upload</a> </h5>
        </div>

      </div>
  </ul>
  {% endif %}
</div>
  {% endblock%}
  {% else %}
  <p>Oops you are not logged in yet please do so. <a href="/login">Log in</a> </p>

{% endif %}

petProject/user/templates/profile/profile_photo.html
{% extends 'home/base_layout.html' %}

{% load crispy_forms_tags %}

    {% block content %}
    <div style="margin-top:50px" class="card">
      <div class="details-header">
        <h3 style="margin-top:50px" >Upload a profile picture so other users can identify you.</h3>
      </div>

      <div class="details-buttons">
        <hr>
        <form class="form-group" enctype="multipart/form-data" method="post" >
          {% csrf_token %}
          {{ form|crispy }}

          <a href="{% url 'home:index' %}">
            <button type="button" style="color:red; margin-bottom: 30px" id="button-hover" class="btn" name="button">Not now</button>
          </a>
          <button type="submit" style="color:blue; margin-bottom: 30px" id="button-hover" class="btn">Upload</button>
        </form>
      </div>
    </div>
    {% endblock %}