petProject/home/urls.py
from django.urls import path
from django.contrib.auth import login
from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("contact-us/", views.contact_us, name="contact"),
]

petProject/petProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("post.urls")),
    path("", include("user.urls")),
    path("", include("django.contrib.auth.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petProject/post/urls.py
from django.urls import path
from django.contrib.auth import login
from . import views

app_name = "post"

urlpatterns = [
    path("create/", views.create_post, name="create"),
    path("<int:pk>/view/", views.view_post, name="view"),
    path("<int:pk>/edit/", views.edit_post, name="edit"),
    path("<int:pk>/edit-comment", views.edit_comment, name="edit_comment"),
    path("<int:pk>/delete", views.delete_post, name="delete"),
    path("<str:username>/archive/", views.archive_post, name="archive_post"),
]

petProject/post/models.py
from django.db import models
from user.models import Account


# Create your models here.


class Post(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True, null=False)
    caption = models.CharField(max_length=1000, null=True)
    is_active = models.BooleanField(default=True)
    is_archived = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    likes = models.ManyToManyField(Account, related_name="like_post", blank=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, null=True, on_delete=models.CASCADE)
    comment = models.CharField(max_length=500, null=True)
    reply = models.ForeignKey(
        "self", null=True, related_name="replies", on_delete=models.CASCADE
    )
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    likes = models.ManyToManyField(Account, related_name="like_comment", blank=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)


class Image(models.Model):
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, null=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/", null=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)

petProject/post/forms.py
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from .models import Post, Comment, Image


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["caption"]


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["comment"]

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields["comment"].label = ""


class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ["image"]

petProject/post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import formset_factory
from django.contrib import messages
from .models import Post, Comment, Image
from .forms import PostForm, CommentForm, ImageForm
from user.models import Account
from django.template.loader import render_to_string
from django.http import JsonResponse

# Create your views here.


def create_post(request):
    ImageFormSet = formset_factory(ImageForm, extra=3, max_num=3)
    if request.method == "POST":
        form = PostForm(request.POST or None)
        formset = ImageFormSet(request.POST or None, request.FILES or None)
        for image_dict in formset.cleaned_data:
            if "image" in image_dict.keys():
                if form.is_valid() and formset.is_valid():
                    post = form.save(commit=False)
                    post.account = request.user
                    post.save()
                    print(formset.cleaned_data)
                    for image_form in formset.cleaned_data:
                        if not image_form:
                            continue
                        else:
                            image = Image(post=post, image=image_form["image"])
                            image.save()
                    messages.success(request, "Post successfully created")
                    return redirect("home:index")
                break
            else:
                messages.error(request, "No image added")
                return redirect(request.path_info)
    else:
        form = PostForm()
        formset = ImageFormSet()
    return render(request, "post/create.html", {"form": form, "formset": formset})


def edit_post(request, pk):
    image_form_class = ImageForm
    post = get_object_or_404(Post, pk=pk)
    ImageFormSet = formset_factory(ImageForm, extra=3, max_num=3)
    form = None
    formset = None
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        formset = ImageFormSet(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            form.save()
            data = Image.objects.filter(post=post)
            for index, form in enumerate(formset):
                if form.cleaned_data:
                    print(form.cleaned_data)
                    if form.cleaned_data["image"] is None:
                        photo = Image(post=post, image=form.cleaned_data.get("image"))
                        photo.save()
                    else:
                        photo = Image(post=post, image=form.cleaned_data.get("image"))
                        d = Image.objects.get(id=data[index].id)
                        d.image = photo.image
                        d.save()
            return redirect("post:view", pk=post.id)
    else:
        form = PostForm(instance=post)
        formset = ImageFormSet(request.POST or None, request.FILES or None)
    return render(
        request, "post/edit_post.html", {"form": form, "formset": formset, "post": post}
    )


def view_post(request, pk):
    form_class = CommentForm
    form = form_class(request.POST or None)
    post = get_object_or_404(Post, pk=pk)
    images = Image.objects.filter(post=post)
    post_liked = False
    comment_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post_liked = True
    comments = Comment.objects.filter(post=post, is_active=True, reply=None).order_by(
        "-date"
    )
    if request.method == "POST":
        if "comment" in request.POST:
            if form.is_valid():
                reply_id = request.POST.get("comment_id")
                comment_qs = None
                if reply_id:
                    print(reply_id)
                    comment_qs = Comment.objects.get(id=reply_id)
                    print(comment_qs)
                new_comment = form.save(commit=False)
                new_comment.post, new_comment.account, new_comment.reply = (
                    post,
                    request.user,
                    comment_qs,
                )
                new_comment.save()
        return redirect(request.path_info)

        if "like_post" in request.POST:
            post.likes.add(request.user)
            post.save()
            post_liked = True
            return redirect(request.path_info)
        if "dislike_post" in request.POST:
            post.likes.remove(request.user)
            post.save()
            post_liked = False
            return redirect(request.path_info)
        if "like_comment" in request.POST:
            comment = Comment.objects.get(pk=request.POST.get("like_comment"))
            comment.likes.add(request.user)
            comment.save()
            comment_liked = True
            return redirect(request.path_info)
        if "dislike_comment" in request.POST:
            comment = Comment.objects.get(pk=request.POST.get("dislike_comment"))
            comment.likes.remove(request.user)
            comment.save()
            comment_liked = False
            return redirect(request.path_info)
    return render(
        request,
        "post/view.html",
        {
            "post": post,
            "comments": comments,
            "form": form,
            "images": images,
            "post_liked": post_liked,
            # "comment_liked": comment_liked,
        },
    )


def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    images = Image.objects.filter(post=post)
    comments = Comment.objects.filter(post=post, is_active=True).order_by("-date")
    if request.method == "POST":
        if "delete_post" in request.POST:
            post.is_active, post.is_deleted = False, True
            post.save()
            return redirect("home:index")
        if "delete_comment" in request.POST:
            comment = Comment.objects.get(pk=request.POST.get("delete_comment"))
            comment.is_active, comment.is_deleted = False, True
            comment.save()
            return redirect("post:view", pk=pk)
    return render(
        request,
        "post/delete_post.html",
        {"post": post, "images": images, "comments": comments},
    )


def edit_comment(request, pk):
    form_class = CommentForm
    comment = get_object_or_404(Comment, pk=pk)
    form = form_class(request.POST or None, instance=comment)
    print(comment.post.id)
    if request.method == "POST":
        if form.is_valid():
            comment.comment = form.cleaned_data["comment"]
            comment.save()
            return redirect("post:view", pk=comment.post.id)
    return render(request, "post/edit_comment.html", {"form": form, "comment": comment})


def archive_post(request, username):
    account = Account.objects.get(username=username)
    posts = Post.objects.filter(is_archived=True, account=account).order_by("-date",)
    images = None
    comments = None
    for post in posts:
        images = post.image_set.all()
        comments = Comment.objects.filter(post=post, is_active=True).order_by("-date")
    if request.method == "POST":
        if "archive_post" in request.POST:
            post = Post.objects.get(id=request.POST.get("post_id"))
            post.is_active, post.is_archived = False, True
            post.save()
            return redirect("home:index")
        if "unarchive_post" in request.POST:
            post = Post.objects.get(id=request.POST.get("post_id"))
            post.is_active, post.is_archived = True, False
            post.save()
            return redirect("home:index")
    return render(
        request,
        "post/archive.html",
        {"posts": posts, "images": images, "comments": comments},
    )

petProject/post/templates/post/archive.html
{% extends 'home/base_layout.html' %}

{% load crispy_forms_tags %}

{% block content %}
<ul>
  {% for post in posts %}
  <li class="card">
    <div class="details-header">
      <a href="/{{ post.account.id }}/profile"><h3>{{ post.account.username | title}}</h3></a>
      <div class="btn-group dropright" style="width:70px">
        <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
          </svg>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <form method="post" action="{% url 'post:archive_post' username=request.user.username %}">
            {% csrf_token %}
              <input type="hidden" name="post_id" value="{{ post.id }}">
            <button type="submit" name="unarchive_post" id="button-hover" class="btn">Show on profile</button>
          </form>
          <a href="/{{ post.id }}/delete">
            <button type="button" name="delete" id="button-hover" class="btn"> Delete</button>
          </a>
        </div>
      </div>

    </div>
        {% for image in images %}
          {% if forloop.first %}
            <a href="/{{ post.id }}/view"><img class="card-image" src="{{ image.image.url }}" alt="Pet image"></a>
          {% endif %}
        {% endfor %}

      <div class="details-buttons">
        <h6>{{ post.caption }}</h6>
          <h6>Likes: {{ post.likes.count }}, Comments: {{ comments.count }}</h6>
      </div>

      </div>


  </li>
  {% endfor %}
</ul>
{% endblock %}

petProject/post/templates/post/comment.html
{% load static %}
{% load crispy_forms_tags %}

<form method="post" >
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" name="comment" style="color:blue; margin-bottom: 20px" id="button-hover" class="btn">Comment</button>
</form>

{% for comment in comments %}
    <hr>
    <div class="flex-comment">
      <blockquote class="blockquote">
         <h6 class="mb-0">{{ comment.comment|capfirst }}</h6>
        <footer class="blockquote-footer"><small><cite title="Source Title">{{ comment.account.username|title }}</cite></small>
          <button type="button" name="button" style="color:blue" id="button-hover"  class="reply-btn btn"> Reply</button>
        </footer>
      </blockquote>
      {% if request.user == comment.account %}

        <div class="btn-group dropright">
          <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
            </svg>
          </button>
          <div class="dropdown-menu">
            <a href="/{{ comment.id }}/edit-comment">
              <button type="button" style="color:blue" name="edit_comment" id="button-hover" class="btn">Edit</button>
            </a>
            <form method="post" action="{% url 'post:delete' pk=post.id %}">
              {% csrf_token %}
            <button type="submit" name="delete_comment" value="{{ comment.id }}" style="color:Red" id="button-hover" class="btn">Delete</button>
            </form>
          </div>
        </div>

      {% endif %}
    </div>
    <div class="replied-comments" style="display:none;">

      {% for reply in comment.replies.all %}
      <blockquote class="blockquote">
        <small><h6 class="mb-0">{{ reply.comment|capfirst }}</h6></small>
        <footer class="blockquote-footer"> <small><cite title="Source Title">{{ reply.account.username|title }}</cite></small>
          {% if request.user == reply.account %}
            <div class="btn-group dropright">
              <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                </svg>
              </button>
              <div class="dropdown-menu">
                <a href="/{{ comment.id }}/edit-comment">
                  <button type="button" style="color:blue" name="edit_comment" id="button-hover" class="btn">Edit</button>
                </a>
                <form method="post" action="{% url 'post:delete' pk=post.id %}">
                  {% csrf_token %}
                <button type="submit" name="delete_comment" value="{{ comment.id }}" style="color:Red" id="button-hover" class="btn">Delete</button>
                </form>
              </div>
            </div>
          {% endif %}
        </footer>

      </blockquote>

      {% endfor %}
      <form method="post" class="reply-form" action=".">
        {% csrf_token %}
        <input type="hidden" name="comment_id" value="{{ comment.id }}">
        {{ form|crispy }}
        <button type="submit" style="color:blue; margin-bottom: 20px" id="button-hover" class="btn">Reply</button>
      </form>
    </div>
    <h6>Likes: {{ comment.likes.count }}</h6>

    <form method="post">
      {% csrf_token %}
        <button type="submit" name="like_comment" value="{{ comment.id }}" style="color:blue" id="button-hover" class="btn">Like</button>
        <button type="submit" name="dislike_comment" value="{{ comment.id }}" style="color:red" id="button-hover" class="btn">Dislike</button>
    </form>
{% endfor %}

petProject/post/templates/post/create.html
{% extends 'home/base_layout.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% if messages %}
      {% for message in messages %}
      <div style="margin-bottom:0;" class="alert alert-danger">
        {{ message }}
      </div>
      {% endfor %}
{% endif %}

<div class="card">
  <div class="details-header">
      <h2 style="margin-top:30px">Create new post</h2>
  </div>
  <div class="details-buttons">
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <span style="opacity:0.5; font-size:12px; ">Note: min 1, max 3.</span>
      {{ formset.management_form }}
      {% for form in formset %}
        {{ form |crispy }}
      {% endfor %}
      <button style="color:blue; margin-bottom: 30px" id="button-hover" type="submit" class="btn">Create</button>
      <a href="{% url 'home:index' %}"><button style="color:red; margin-bottom: 30px" id="button-hover" type="button" class="btn">Cancel</button></a>
    </form>
  </div>
</div>
{% endblock%}

petProject/post/templates/post/delete_post.html
{% extends 'home/base_layout.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="card">
  <div class="details-header">
    <h4>Are you sure you want to delete this post forever?</h4>
    <form  method="post">
      {% csrf_token %}
      <button type="submit" name="delete_post" style="color:red" id="button-hover" class="btn">Yes</button>
      <a href="/{{ post.id }}/view">
        <button type="button" style="color:blue" name="button" id="button-hover" class="btn">No</button>
      </a>
    </form>
  </div>
  <div class="details-content">
    {% for image in images %}
    <div class="w3-content w3-display-container">
      <div class="w3-display-container mySlides">
        <img class="card-image" src="{{ image.image.url }}" style="width:100%">
        <button class="w3-button w3-display-left w3-black" onclick="plusDivs(-1)">&#10094;</button>
        <button class="w3-button w3-display-right w3-black" onclick="plusDivs(1)">&#10095;</button>
      </div>
    </div>
    {% endfor %}
  </div>


  <div class="details-buttons">
    <h6>{{ post.caption }}</h6>
    <h6>Likes: {{ post.likes.count }}, Comments: {{ comments.count }} </h6>
  </div>
</div>

{% endblock %}

petProject/post/templates/post/edit_comment.html
 {% extends 'home/base_layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card">
  <div class="details-header">
    <h2 style="margin-top:30px">Edit comment</h2>
  </div>
  <div class="details-buttons">
    <form  method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <a href="/{{ comment.post.id }}/view"><button style="color:red; margin-bottom: 30px" type="button" id="button-hover" class="btn">Cancel</button></a>
      <button type="submit" style="color:blue; margin-bottom: 30px;" id="button-hover" class="btn">Update comment</button>
    </form>
  </div>
</div>
{% endblock %}

petProject/post/templates/post/edit_post.html
{% extends 'home/base_layout.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="card">
  <div class="details-header">
    <h2 style="margin-top:30px">Edit post</h2>
  </div>
  <div class="details-buttons">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      {{ formset.management_form }}
      {% for form in formset %}
        {{ form |crispy }}
      {% endfor %}
      <a href="/{{ post.id }}/view"><button style="color:red; margin-bottom: 30px" type="button" id="button-hover" class="btn">Cancel</button></a>
      <button type="submit" style="color:blue; margin-bottom: 20px" id="button-hover" class="btn">Update post</button>
    </form>
  </div>
</div>
{% endblock %}

petProject/post/templates/post/view.html
{% extends 'home/base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<button onclick="topFunction()" id="myBtn" title="Go to top">Back to top</button>
<div class="card">
  <div class="details-header">
    <a href="/{{ post.account.username }}/profile"><h3 class="details-header">{{ post.account.username | title}}</h3></a>
    {% if request.user == post.account %}
      <div class="btn-group dropright" style="width:70px">
        <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
          </svg>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a href="/{{ post.id }}/edit">
            <button type="button" name="edit" style="color:blue" id="button-hover" class="btn"> Edit</button>
          </a>

          <form method="post" action="{% url 'post:archive_post' username=request.user.username %}">
            <input type="hidden" name="post_id" value="{{ post.id }}">
            {% csrf_token %}
            <button type="submit" name="archive_post" value="archive" style="color:blue" id="button-hover" class="btn"> Archive</button>
          </form>
          <a href="/{{ post.id }}/delete">
            <button type="button" name="delete" style="color:Red" id="button-hover" class="btn"> Delete</button>
          </a>
        </div>
      </div>
    {% endif %}
  </div>

  <div class="details-content">
    {% for image in images %}
    <div class="w3-content w3-display-container">
      <div class="w3-display-container mySlides">
        <img class="card-image" src="{{ image.image.url }}" style="width:100%">
        <button class="w3-button w3-display-left w3-black" onclick="plusDivs(-1)">&#10094;</button>
        <button class="w3-button w3-display-right w3-black" onclick="plusDivs(1)">&#10095;</button>
      </div>
    </div>
    {% endfor %}
  </div>

  <div class="details-buttons">
      <h6>{{ post.caption }}</h6>
        <h6>Likes: {{ post.likes.count }}, Comments: {{ comments.count }} </h6>

      <form method="post" >
        {% csrf_token %}
        {% if post_liked %}
          <button type="submit" name="dislike_post" value="{{ post.id }}" style="color:red" id="button-hover" class="btn">Dislike</button>
        {% else %}
          <button type="submit" name="like_post" value="{{ post.id }}" style="color:blue" id="button-hover" class="btn">Like</button>
        {% endif %}
      </form>
      
      {% include 'post/comment.html' %}
  </div>
</div>

{% endblock %}