petProject/home/urls.py
from django.urls import path
from django.contrib.auth import login
from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("contact-us/", views.contact_us, name="contact"),
]

petProject/petProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("post.urls")),
    path("", include("user.urls")),
    path("", include("django.contrib.auth.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petProject/home/models.py
from django.db import models

# Create your models here.

petProject/post/models.py
from django.db import models
from user.models import Account


# Create your models here.


class Post(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True, null=False)
    caption = models.CharField(max_length=1000, null=True)
    is_active = models.BooleanField(default=True)
    is_archived = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    likes = models.ManyToManyField(Account, related_name="like_post", blank=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, null=True, on_delete=models.CASCADE)
    comment = models.CharField(max_length=500, null=True)
    reply = models.ForeignKey(
        "self", null=True, related_name="replies", on_delete=models.CASCADE
    )
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    likes = models.ManyToManyField(Account, related_name="like_comment", blank=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)


class Image(models.Model):
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, null=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/", null=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)

petProject/home/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from post.models import Post, Comment, Image
from user.models import Account


# Create your views here.


@login_required
def index(request):
    posts = Post.objects.filter(is_active=True).order_by("-date",)
    images = None
    comments = None
    for post in posts:
        images = post.image_set.all()
        comments = Comment.objects.filter(post=post, is_active=True, reply=None)
    return render(
        request,
        "home/index.html",
        {"posts": posts, "images": images, "comments": comments},
    )


def contact_us(request):
    return render(request, "home/contact_us.html", {})

petProject/home/templates/home/alerts.html
{% load static %}
{% if messages %}
      {% for message in messages %}
      <div style="margin-bottom: 0; " class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
      {% endfor %}
{% endif %}
<script src="{% static 'style.js' %}">

</script>

petProject/home/templates/home/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>The Pet Gallery</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://bootswatch.com/4/litera/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" >
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>

    {% include 'home/nav_bar.html' %}
    <div class="background-image">
      {% block content %}
      {% endblock %}
    </div>



    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'style.js' %}"></script>
  </body>
</html>

petProject/home/templates/home/contact_us.html
{% extends 'home/base_layout.html' %}

{% block content %}

<div class="card">
  
</div>

{% endblock %}

petProject/home/templates/home/edit.html
{% extends 'home/base_layout.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="card">
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
  <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

petProject/home/templates/home/index.html
{% extends 'home/base_layout.html' %}
{% load static %}
{% block content %}
{% include 'home/alerts.html' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<button onclick="topFunction()" id="myBtn" title="Go to top">Back to top</button>
<ul>
  {% for post in posts %}
    <li class="card">
      <div class="details-header">
        <a  href="{{ post.account.username }}/profile"><h3 >{{ post.account.username | title}}</h3></a>
      </div>
        {% for image in post.image_set.all %}
          {% if forloop.first %}
            <a href="/{{ post.id }}/view"><img class="card-image" src="{{ image.image.url }}" alt="Pet image"></a>
          {% endif %}
        {% endfor %}
        <div class="details-buttons">
          <h6>{{ post.caption }}</h6>
          <h6>Likes: {{ post.likes.count }}</h6>
        </div>
    </li>
  {% endfor %}
</ul>
{% endblock %}

petProject/home/templates/home/nav_bar.html
<div class="navbar-stick">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home:index' %}">The Pet Gallery</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false"
      aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarColor03">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home:index' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/{{ request.user.username }}/profile">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:contact' %}">Contact us</a>
            </li>
            <li class="nav-item">
              <a href="/create" class="create-post" style="margin-right:20px">
                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                  <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                  <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                </svg>
              </a>
            </li>
          </ul>

            <a  href="/logout"><button style="color:red;"  id="button-hover" class="btn" type="button">Logout</button></a>
        {% endif %}
      </div>
    </nav>
</div>

petProject/home/templates/home/profile.html
{% extends 'home/base_layout.html' %}
{% load static %}
{% if user.is_authenticated %}
  {% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% include 'home/alerts.html' %}
      <div class="background">
        <div class="details-header">
          <div class="profile-picture">
            {% if image == None %}
              <img src="{% static 'default_img.jpg' %}" alt="">
            {% else %}
              <img src="{{ image.image.url }}" alt="Profile Photo">
            {% endif %}
          </div>
          <div class="profile-info">
            <ul>
              {% if account.username %}
                <li>Username: {{ account.username | title  }}</li>
              {% endif %}
              {% if account.animal %}
                <li>Animal: {{ account.animal | title }}</li>
              {% endif %}
              {% if account.breed %}
                <li>Breed: {{ account.breed | title }}</li>
              {% endif %}
              {% if account.bio %}
                <li>Bio: {{ account.bio | title }}</li>
              {% endif %}
            </ul>
          </div>
            {% if account == request.user %}
            <div class="btn-group dropright" style="width:70px; height:50px; margin-top:20px">
              <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                </svg>
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a href="/{{ request.user.username }}/edit-profile">
                  <button type="button" name="archive" id="button-hover" style="color:blue" class="btn">Edit Profile</button>
                </a>
                <a href="/{{ account.username }}/archive">
                  <button type="button" name="archive" id="button-hover" style="color:blue" class="btn">Archive</button>
                </a>
                <a href="/password_change">
                  <button style="color:blue" id="button-hover" class="btn" type="button">Change password</button>
                </a>
                <a href="/logout">
                  <button style="color:red"class="btn" id="button-hover" type="button">Logout</button>
                </a>

              </div>
            </div>
            {% endif %}
      </div>

    </div>
<div class="details-buttons">
  {% if posts %}
  <ul class="profile-posts">
    {% for post in posts %}
    <li>
      <div class="post-card">
        {% for image in post.image_set.all %}
          {% if forloop.first %}
            <a href="/{{ post.id }}/view"><img class="card-image" src="{{ image.image.url }}" alt="Pet image"></a>
          {% endif %}
        {% endfor %}
      </div>
    </li>
    {% endfor %}
  {% else %}
      <div class="no-post">
        <img src="https://img.icons8.com/clouds/100/000000/dog-paw-print.png"/>
        <div class="">
          <h5>No post yet <a style="color:blue;" href="/create">Upload</a> </h5>
        </div>

      </div>
  </ul>
  {% endif %}
</div>
  {% endblock%}
  {% else %}
  <p>Oops you are not logged in yet please do so. <a href="/login">Log in</a> </p>

{% endif %}